# Generated by Django 3.0.5 on 2020-04-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_model',
            old_name='age',
            new_name='Job',
        ),
    ]
