# Generated by Django 3.0.5 on 2020-04-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200420_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_model',
        ),
    ]
