# Generated by Django 3.0.5 on 2020-04-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_login_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_model',
            name='Job',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='login_model',
            name='name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='login_model',
            name='place',
            field=models.CharField(max_length=264),
        ),
    ]
